name:                db-user-haskell
version:             0.1.0.0
github:              "joshuadeleon/db-user-haskell"
license:             BSD3
author:              "Joshua De Leon"
maintainer:          "example@example.com"
copyright:           "2018 Joshua De Leon"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joshuadeleon/db-user-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- postgresql-simple
- text
- configurator
- bytestring

library:
  source-dirs: src

executables:
  db-user-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-user-haskell
    default-extensions: OverloadedStrings, DeriveGeneric

tests:
  db-user-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - db-user-haskell
